server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: file:media, classpath:/static
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_APIKEY}
            client-secret: ${KAKAO_CLIENTSECRET}
            provider: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - account_email
            client-name: Kakao
            client-authentication-method: client_secret_post
          naver:
            client-id: ${NAVER_CLIENTID}
            client-secret: ${NAVER_CLIENTSECRET}
            client-name: Naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - email
            authorization-grant-type: authorization_code
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope:
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: google
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
    default-encoding: UTF-8
    port: 587

jwt:
  secret:
    refresh: ${JWT_REFRESH}
    access: ${JWT_ACCESS}