server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: file:media, classpath:/static
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_APIKEY}
            client-secret: ${KAKAO_CLIENTSECRET}
            provider: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id